services:
  app_nami:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PSS: ${DB_PSS}
      TOKEN_SECRET: ${TOKEN_SECRET}
      APP_ENV: ${APP_ENV}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    restart: always
