spring:
  application:
    name: nami_nami
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PSS}

    driver-class-name: org.postgresql.Driver
    # On render temporal config
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
          static-locations: classpath:/static/

jwt:
  secret: ${TOKEN_SECRET}

nami:
  env: ${APP_ENV:development}

server:
  servlet:
    context-path: /api/v1

cloudinary:
  CLOUD_NAME: ${CLOUD_NAME}
  API_KEY: ${CLOUD_API_KEY}
  API_SECRET: ${CLOUD_API_SECRET}

springdoc:
  api-docs:
    path: /docs/open-api
    version: OPENAPI_3_1
  swagger-ui:
    path: /docs/swagger-ui/index.html
    title: Ñami Ñami API Docs